# Generated by Django 2.1.1 on 2018-09-04 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('desc', models.TextField(max_length=4096)),
                ('poster', models.ImageField(upload_to='')),
                ('tag', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('latest', models.IntegerField()),
                ('updated', models.DateTimeField()),
                ('count', models.BigIntegerField()),
            ],
            options={
                'ordering': ('title', 'count'),
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(max_length=64000)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.Book')),
            ],
            options={
                'ordering': ('section',),
            },
        ),
    ]
