# Generated by Django 2.1.1 on 2018-09-06 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookOriginalSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('url', models.URLField(max_length=1024)),
                ('all', models.URLField(max_length=1024)),
                ('activate', models.BooleanField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('title',)},
        ),
        migrations.RemoveField(
            model_name='book',
            name='count',
        ),
        migrations.AlterField(
            model_name='book',
            name='latest',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='poster',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='book',
            name='updated',
            field=models.DateTimeField(null=True),
        ),
    ]
