# Generated by Django 2.1.1 on 2018-09-10 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_auto_20180907_0338'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('title', 'author')},
        ),
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together={('book', 'section')},
        ),
    ]
